version: '3'
services:
  servicio1:
    container_name: api_allora
    build: 
      context: API_AlLoRa
      dockerfile: Dockerfile.apiallora
    ports:
      - 8004:8004
    devices:
      - /dev/ttyAMA3:/dev/ttyAMA3
    environment:
      - SERIAL_PATH=/dev/ttyAMA3
      - ALLORA_FILES=/allora_files
    volumes:
      - /home/rak/AlLoRa_files:/allora_files
    networks:
      - mi_red
    
  servicio2:
    container_name: allora_page
    build:
      context: AlLoRaPage
      dockerfile: Dockerfile.page
    environment:
      - PORT_API=8004
      - URL=http://servicio1:8004
    ports:
      - 8005:8005
    networks:
      - mi_red

networks:
  mi_red:
    external: true